SGX improvements
enarx/enarx pull request #1081
Opened 2021-11-01 17:08 UTC by npmccallum

2021-11-09 10:21 UTC, haraldh commented
stderr is normally not line buffered for obvious reasons... you also don't have to call flush, e.g.

2021-11-09 10:23 UTC, haraldh commented
Although the `debug!` and `debugln!` could call some `flush()` like routine here.

2021-11-09 10:24 UTC, haraldh requested changes

2021-11-09 10:24 UTC, haraldh commented on internal/shim-sgx/src/handler/mod.rs
> +                        debugln!(h, "unsupported opcode: 0x{:04x}", r);
```suggestion
                        debugln!(h, "unsupported opcode: {:#04x}", r);
```

2022-01-21 21:20 UTC, npmccallum commented
I'm rejecting this PR.

2022-01-21 21:20 UTC, closed without merging