feat(sgx): shim_address() for normal and naked functions
enarx/enarx pull request #1561
Opened 2022-03-17 17:50 UTC by jarkkojs

Closes: #1560
Signed-off-by: Jarkko Sakkinen <jarkko@profian.com>

2022-03-17 17:52 UTC, jarkkojs commented on internal/shim-sgx/src/lib.rs
> +pub fn shim_address() -> usize {
missing `#[inline]`. I'll add it.

2022-03-17 17:59 UTC, npmccallum commented
@jarkkojs We used to have a simpler function for this. But it looks like it was removed during the gdb effort. I want @haraldh to review this just in case I missed something. But otherwise, LGTM.

2022-03-21 13:23 UTC, jarkkojs commented
@haraldh ?

2022-03-21 13:56 UTC, haraldh commented
> @haraldh ?

looking

2022-03-21 14:05 UTC, haraldh requested changes

2022-03-21 14:05 UTC, haraldh commented on internal/shim-sgx/src/main.rs
> +        "call   {DYN_RELOC}",                        // relocate the dynamic symbols
```diff
diff --git a/internal/shim-sgx/src/main.rs b/internal/shim-sgx/src/main.rs
index 0530b1c0..3f205032 100644
--- a/internal/shim-sgx/src/main.rs
+++ b/internal/shim-sgx/src/main.rs
@@ -19,7 +19,9 @@ extern crate rcrt1;
 
 use core::arch::asm;
 
-use shim_sgx::{entry, handler, ATTR, BLOCK_SIZE, ENARX_EXEC_START, ENCL_SIZE_BITS, MISC};
+use shim_sgx::{
+    entry, handler, ATTR, BLOCK_SIZE, ENARX_EXEC_START, ENARX_SHIM_ADDRESS, ENCL_SIZE_BITS, MISC,
+};
 
 #[panic_handler]
 #[cfg(not(test))]
@@ -166,7 +168,7 @@ unsafe extern "sysv64" fn relocate() {
         "push   r11",
 
         "lea    rdi,    [rip + _DYNAMIC]",           // rdi = address of _DYNAMIC section
-        "lea    rsi,    [rip + ENARX_SHIM_ADDRESS]", // rsi = enclave start address mask
+        "lea    rsi,    [rip + {ENARX_SHIM_ADDRESS}]", // rsi = enclave start address mask
         "call   {DYN_RELOC}",                        // relocate the dynamic symbols
 
         "pop    r11",
@@ -182,6 +184,7 @@ unsafe extern "sysv64" fn relocate() {
         "ret",
 
         DYN_RELOC = sym rcrt1::dyn_reloc,
+        ENARX_SHIM_ADDRESS = sym ENARX_SHIM_ADDRESS,
         options(noreturn)
     )
 }
```

2022-03-21 14:10 UTC, haraldh commented on internal/shim-sgx/src/main.rs
> +        "call   {DYN_RELOC}",                        // relocate the dynamic symbols
optional

2022-03-21 16:23 UTC, jarkkojs commented on internal/shim-sgx/src/main.rs
> +        "call   {DYN_RELOC}",                        // relocate the dynamic symbols
Changes done, I'll just run `cargo test` as a sanity check.

2022-03-21 16:26 UTC, jarkkojs commented on internal/shim-sgx/src/main.rs
> +        "lea    rsi,    [rip + {ENARX_SHIM_ADDRESS}]", // rsi = enclave start address mask
`cargo test` passed.

2022-03-21 16:29 UTC, jarkkojs commented on internal/shim-sgx/src/main.rs
> +        "lea    rsi,    [rip + {ENARX_SHIM_ADDRESS}]", // rsi = enclave start address mask
`HIDDED` marks it as a static symbol.

2022-03-21 16:32 UTC, haraldh approved these changes

2022-03-21 16:33 UTC, merged