Snp vcek attestation
enarx/enarx pull request #1581
Opened 2022-03-22 16:45 UTC by haraldh

2022-03-23 12:30 UTC, npmccallum commented
@haraldh Note, you can find a valid instance of the `Evidence` type [here](https://github.com/profianinc/steward/blob/main/src/main.rs#L387-L391). You can encode it to bytes using the `.to_vec()` method. Then you can parse the bytes [here](https://lapo.it/asn1js/) to see which bytes you need to make dynamic.

2022-03-23 17:34 UTC, haraldh commented
Got the basics ready. Will post an updated PR tomorrow

2022-03-24 19:17 UTC, npmccallum requested changes
@haraldh You are encoding one too many layers here. You are encoding the `Extension` type when you should be encoding the inner `Evidence` type. The wasmldr code will wrap the encoded `Evidence` in an `Extension`.

2022-03-25 12:52 UTC, haraldh commented
> @haraldh You are encoding one too many layers here. You are encoding the `Extension` type when you should be encoding the inner `Evidence` type. The wasmldr code will wrap the encoded `Evidence` in an `Extension`.

@npmccallum fixed

2022-03-25 18:49 UTC, npmccallum approved these changes

2022-03-25 18:49 UTC, merged