feat: resurrect the nil backend
enarx/enarx pull request #1782
Opened 2022-04-25 21:00 UTC by npmccallum

This should aid the testing of documentation on systems with no kvm
support (such as GitHub runners).

Signed-off-by: Nathaniel McCallum <nathaniel@profian.com>

2022-04-25 21:00 UTC, npmccallum commented
@haraldh I didn't get this working yet. But if you see something obvious, I'm all ears.

2022-04-25 21:05 UTC, haraldh commented
I'll look into this tomorrow.

2022-04-26 11:44 UTC, haraldh requested changes

2022-04-26 11:44 UTC, haraldh commented on src/backend/nil.rs
> +            );
```suggestion
            let mut rwx = 0;

            if phdr.p_flags & PF_R != 0 {
                rwx |= libc::PROT_READ;
            }
            if phdr.p_flags & PF_W != 0 {
                rwx |= libc::PROT_WRITE;
            }
            if phdr.p_flags & PF_X != 0 {
                rwx |= libc::PROT_EXEC;
            }

            if unsafe { libc::mprotect(map.addr() as _, map.size(), rwx) } != 0 {
                return Err(std::io::Error::last_os_error().into());
            }
```

2022-04-26 11:44 UTC, haraldh commented on src/backend/nil.rs
> +            );
This fixed it!

2022-04-27 13:58 UTC, npmccallum commented
Closed in favor of #1794.

2022-04-27 13:58 UTC, closed without merging