feat: validate workload digests
enarx/enarx pull request #2118
Opened 2022-08-04 18:00 UTC by rvolosatovs

Closes #2033
Closes #1854 

Blocked by https://github.com/profianinc/drawbridge/pull/246

2022-08-04 19:23 UTC, rvolosatovs commented
If this is merged before https://github.com/profianinc/drawbridge/pull/249 is merged, tagged and deployed. Drawbridge integration in `enarx` tool will break.
I will work on fixing that soon

2022-08-05 11:19 UTC, haraldh requested changes

2022-08-05 11:19 UTC, haraldh commented on crates/exec-wasmtime/src/loader/requested.rs
> +    );
```suggestion
fn get_wasm(root: Entity<'_, impl Scope, scope::Node>, entry: &TreeEntry) -> Result<Vec<u8>> {
    ensure!(
        entry.meta.mime.essence_str() == WASM_MEDIA_TYPE,
        "invalid `{}` media type `{}`",
        *PACKAGE_ENTRYPOINT,
        entry.meta.mime.essence_str()
    );
```

2022-08-05 11:19 UTC, haraldh commented on crates/exec-wasmtime/src/loader/requested.rs
> +    );
```suggestion
    let entry = if let Some(entry) = dir.get(&PACKAGE_CONFIG) {
        entry
    } else {
        return Ok((wasm, None));
    };
    ensure!(
        entry.meta.mime.essence_str() == TOML_MEDIA_TYPE,
        "invalid `{}` media type `{}`",
        *PACKAGE_CONFIG,
        entry.meta.mime.essence_str()
    );
```

2022-08-05 13:58 UTC, haraldh approved these changes

2022-08-05 14:14 UTC, merged