ci(sgx): test for SGX2 before setting `cfg(host_can_test_sgx)`
enarx/enarx pull request #2307
Opened 2022-11-09 14:39 UTC by haraldh

Fixes: https://github.com/enarx/enarx/issues/2235

Signed-off-by: Harald Hoyer <harald@profian.com>

2022-11-09 15:03 UTC, rjzak commented
Tests passed!

2022-11-09 21:06 UTC, npmccallum requested changes
Please fix clippy warnings on Windows/MacOS.

2022-11-10 09:14 UTC, haraldh commented
> Please fix clippy warnings on Windows/MacOS.

@npmccallum done

2022-11-11 13:41 UTC, npmccallum approved these changes

2022-11-11 13:41 UTC, merged