feat(drawbridge): add client secrets login
enarx/enarx pull request #2356
Opened 2022-11-18 19:18 UTC by rvolosatovs

This is based on top of #2354 

Original description:
>This adds logging in with client credential grant for machine-2-machine interactions, like bots for uploading data to a Drawbridge instance.

Additionally, this adds an `oidc-flow` flag, which defaults to `device` and fixes few missed cases in #2354 (e.g. `enarx user register`)

- Support specifying a `client-secret-id` on `enarx user register`
- Reorganize code for clarity
- Remove redundant clones and borrows

2022-11-22 15:26 UTC, puiterwijk approved these changes
This looks decent to me.

2022-11-22 21:07 UTC, bstrie requested changes
How difficult would it be to add integration tests for the new CLI options? Would the OIDC mock need to be extended?

2022-11-24 04:25 UTC, puiterwijk commented
@bstrie The OIDC mock doesn't actually exercise the OIDC login flows: it starts with a pre-existing authentication token, and just skips over all of the code touched by this PR.

2022-11-24 18:50 UTC, rvolosatovs commented
> How difficult would it be to add integration tests for the new CLI options? Would the OIDC mock need to be extended?

Since you're in charge of CLI, please either file an issue about it and add these tests or add them here.
This is really just for internal use (at least for now)

2022-11-29 15:42 UTC, bstrie approved these changes

2022-11-29 15:42 UTC, merged