chore(deps): update some dependencies
enarx/enarx pull request #2560
Opened 2023-12-06 04:50 UTC by rjzak

A lot of crates have had breaking dependencies the past few months, trying to work through them.

2023-12-13 03:46 UTC, rjzak commented
@haraldh I could use your wisdom...

What I don't understand is why this trait

https://github.com/enarx/enarx/blob/9577e8fcf26af58b99f63e40d0b530f90c834c50/src/backend/mod.rs#L120-L139

is no longer working for `sgx::signature::Signature` here:

https://github.com/enarx/enarx/blob/9577e8fcf26af58b99f63e40d0b530f90c834c50/src/backend/sgx/builder.rs#L135-L138

Even though these lines didn't change...

2023-12-13 12:58 UTC, haraldh requested changes

2023-12-13 12:58 UTC, haraldh commented on src/cli/sign.rs
> +use sgx::signature::{Author, Body};
Hmm.. you changed `Signature` and `unsafe impl ByteSized for Signature` does not apply anymore to `sgx::signature::Signature` then

2023-12-14 01:56 UTC, rjzak commented
@haraldh I got https://github.com/enarx/enarx/pull/2561 working. But I'm not sure which is better:

* This PR:
```rust
const ES384: AlgorithmIdentifierOwned = AlgorithmIdentifierOwned {
    oid: ECDSA_WITH_SHA_384,
    parameters: None,
};
``` 

or other PR: https://github.com/enarx/enarx/pull/2561
```rust
const ES256: AlgorithmIdentifierRef<'static> = AlgorithmIdentifierRef {
    oid: ECDSA_WITH_SHA_256,
    parameters: None,
};
```

I'm guessing the second one, which I un-drafted.

2023-12-16 01:17 UTC, rjzak commented
Superseded by #2561

2023-12-16 01:17 UTC, closed without merging